default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host: "localhost"
  port: "5432"
  username: "postgres"
  password: "example"
  database: workspace_development

test:
  <<: *default
  host: "localhost"
  port: "5432"
  username: "postgres"
  password: "example"
  database: workspace_test

#production:
#  <<: *default
#  url: <%#= ENV.fetch("DATABASE_URL", "") %>

production:
  <<: *default
  database: workspace_production
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
